pub_review/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name= 'pub_review'
urlpatterns = [
    path('',views.index, name ='index'),

    # Question and Answer URLs
    path('questions/',views.list_questions,name="questions"),
    path('question/<int:question_id>/',views.detail, name = 'detail'),
    path('question/create/',views.question_create, name = 'question_create'),
    path('answer/create/<int:question_id>/',views.answer_create, name = 'answer_create'),
    path('question/modify/<int:question_id>/',views.question_modify,name='question_modify'),
    path('question/delete/<int:question_id>/',views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/',views.answer_modify,name='answer_modify'),
    path('answer/delete/<int:answer_id>/',views.answer_delete, name='answer_delete'),


    # Login URLs
    path('login/',views.user_login, name= 'login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),

    # Pub URLs
    path('search/',views.list_pubs, name='search'),
    path('pub/<int:pub_id>/',views.showPub,name="pubDetail"),
    path('pub/create/',views.pub_create, name= 'pub_create'),
    path('pub/modify/<int:pub_id>/',views.pub_modify,name='pub_modify'),
    path('pub/delete/<int:pub_id>/',views.pub_delete, name='pub_delete'),

    #Review URLs
    path('pub/<int:pub_id>/review/<int:review_id>/',views.showReview, name = 'reviewDetail'),
    path('pub/<int:pub_id>/review/create/',views.review_create, name = 'review_create'),
    path('pub/<int:pub_id>/review/modify/<int:review_id>/',views.review_modify,name='review_modify'),
    path('pub/<int:pub_id>/review/delete/<int:review_id>/',views.review_delete, name='review_delete'),

    #Pub_Question URLs
    path('pub/<int:pub_id>/question/<int:Pub_Question_id>/',views.showPub_Question, name = 'Pub_QuestionDetail'),
    path('pub/<int:pub_id>/question/create/',views.Pub_Question_create, name = 'Pub_Question_create'),
    path('pub/<int:pub_id>/question/<int:Pub_Question_id>/answer/create/',views.Pub_Answer_create, name = 'Pub_Answer_create'),
    path('pub/<int:pub_id>/question/modify/<int:Pub_Question_id>/',views.Pub_Question_modify,name='Pub_Question_modify'),
    path('pub/<int:pub_id>/question/delete/<int:Pub_Question_id>/',views.Pub_Question_delete, name='Pub_Question_delete'),
    path('pub/<int:pub_id>/question/<int:Pub_Question_id>/answer/modify/<int:Pub_Answer_id>/',views.Pub_Answer_modify,name='Pub_Answer_modify'),
    path('pub/<int:pub_id>/question/<int:Pub_Question_id>/answer/delete/<int:Pub_Answer_id>/',views.Pub_Answer_delete, name='Pub_Answer_delete'),

    #User URLs
    path('user/<int:user_id>/',views.showUserProfile,name="userProfile"),
    path('user/modify/<int:user_id>/',views.userProfile_modify,name='user_modify'),
    path('user/delete/<int:user_id>/',views.userProfile_delete, name='user_delete'),

    #Voter URLs
    path('vote/pub/<int:pub_id>/',views.vote_pub,name="vote_pub"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team4b_pub_review/urls.py
from django.contrib import admin
from django.urls import include, path
from pub_review import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('pub-review/', include('pub_review.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pub_review/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    # These are commented out as they are stored in the django models.User table
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='userProfile_images',blank= True,null=True, default='userProfile_images/default-profile.png')
    firstName = models.CharField(max_length=128,blank= True,null=True)
    lastName = models.CharField(max_length=128,blank=True,null=True)
    sex = models.CharField(max_length=10,blank=True,null=True)
    age = models.IntegerField(blank=True,null=True)
    nationality = models.CharField(max_length=40,blank=True,null=True)

    def __str__(self):
        return self.user.username

class Pub(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE,related_name='owner_pub')
    pubName = models.CharField(max_length=128)
    city = models.CharField(max_length=128)
    streetName = models.CharField(max_length=128)
    postcode = models.CharField(max_length=7) # 7 chars long, longest postcode is "AB123YZ" format
    picture = models.ImageField(upload_to='pubProfile_images', blank=True,null=True)
    voter = models.ManyToManyField(User,related_name='voter_pub')
    def __str__(self):
        return self.pubName
    
class Question(models.Model):
    subject = models.CharField(max_length =200)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    pub = models.ForeignKey(Pub,on_delete=models.CASCADE, null=True, blank=True)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    content = models.TextField()
    pub = models.ForeignKey(Pub,on_delete=models.CASCADE, null=True, blank=True)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    pub = models.ForeignKey(Pub,on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    picture = models.ImageField(upload_to='review_images', blank=True,null=True)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

class FavoritePubs(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    pub1 = models.CharField(max_length=100,null=True, blank=True)
    pub2 = models.CharField(max_length=100,null=True, blank=True)
    pub3 = models.CharField(max_length=100,null=True, blank=True)
    pub4 = models.CharField(max_length=100,null=True, blank=True)
    pub5 = models.CharField(max_length=100,null=True, blank=True)

    def __str__(self):
        return self.user.user.username + "'s top 5"

pub_review/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Question,Pub,User,Answer,Review,UserProfile,FavoritePubs
from django.utils import timezone
from .forms import QuestionForm, AnswerForm,UserForm,UserProfileForm,PubProfileForm,ReviewForm,FavoritePubForm
from django.core.paginator import Paginator
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import auth,messages
from django.db.models import Q, Count
# Create your views here.

def index(request):
    top5_pubs = Pub.objects.annotate(num_votes = Count('voter')).order_by('-num_votes')[:5]
    recent_reviews= Review.objects.order_by('-create_date')[:5]
    context ={'top5_pubs':top5_pubs, 'recent_reviews':recent_reviews}

    # Google Maps Integration
    key = "AIzaSyB5Prlm7hNvW0P2uxPQ71FKdZUsAFHhoUM"


    if top5_pubs.exists():
        context["top_pub"] = top5_pubs[0]
        placeData = [getattr(top5_pubs[0], 'pubName') , getattr(top5_pubs[0], 'streetName'), getattr(top5_pubs[0], 'city')]  # array of strings, containing pub name, street address, city
        for counter in range (0,3):
            #print("Debugging views.py:ln 25 \n placeData [{}] value = {}".format(counter, placeData[counter]))
            placeData[counter] = placeData[counter].replace(" ", "%20") # maps api uses %20 for spaces

        mapURL = "https://www.google.com/maps/embed/v1/place?key={0}&q={1},{2},{3}".format(key,placeData[0],placeData[1],placeData[2])

        context['mapURL'] = mapURL

    return render(request,'pub_review/home.html',context)

def list_questions(request):
    page = request.GET.get('page', 1)  # Page
    kw = request.GET.get('kw','')
    question_list = Question.objects.order_by('-create_date')

    search = request.GET.get("qSearch")

    # If the user has entered a search term, filter based on that term
    if search != None:
     question_list = Question.objects.filter(subject__contains=search)

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()

    # Paging
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pub_review/Q&A.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pub_review/question_detail.html', context)

@login_required(login_url='pub_review:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.question = question
            answer.create_date = timezone.now()
            answer.save()
            return redirect('pub_review:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pub_review/question_detail.html', context)

@login_required(login_url='pub_review:login')
def answer_modify(request,answer_id):
    answer = get_object_or_404(Answer,pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'No Authentication')
        return redirect('pub_review:detail',question_id=answer.question.id)

    if request.method =="POST":
        form = AnswerForm(request.POST,instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pub_review:detail',question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'form' : form}
    return render(request,'pub_review/answer_form.html',context)

@login_required(login_url='pub_review:login')
def answer_delete(request,answer_id):
    answer = get_object_or_404(Answer,pk=answer_id)
    if request.user != answer.author:
        messages.error(request, "No Authentication")
        return redirect('pub_review:detail',question_id=answer.question.id)
    answer.delete()
    return redirect('pub_review:detail',question_id=answer.question.id)

@login_required(login_url='pub_review:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pub_review:questions')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pub_review/question_form.html', context)


from django.shortcuts import render

@login_required(login_url='pub_review:login')
def question_modify(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    if request.user != question.author:
        messages.error(request,'No Authentication')
        return redirect('pub_review:detail',question_id=question.id)

    if request.method =="POST":
        form = QuestionForm(request.POST,instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('pub_review:detail',question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form' : form}
    return render(request,'pub_review/question_form.html',context)

@login_required(login_url='pub_review:login')
def question_delete(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    if request.user != question.author:
        messages.error(request, "No Authentication")
        return redirect('pub_review:detail',question_id=question.id)
    question.delete()
    return redirect('pub_review:questions')

def signup(request):
    registered = False
    if request.method == 'POST':
        # most of this sourced from tango with django online tutorial
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            if request.POST['password1'] == request.POST['password2']:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                userProfile = UserProfile.objects.create(user=user)
                FavoritePubs.objects.create(user=userProfile)
                auth.login(request, user)
                user_id = user.id
                return redirect('pub_review:user_modify', user_id=user_id)
            elif  request.POST['password1'] != request.POST['password2']: 
                messages.error(request, 'Passwords do not match')
        else:  
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request, 'pub_review/signup.html', context={'user_form': user_form, 'registered': registered})

def user_login(request):
    if request.method == "POST":
        # POST request, try to log user in using credentials sent
        username = request.POST.get("username")
        password = request.POST.get("password")

        #use django built in functionality to verify login details
        user = authenticate(username=username, password=password)

        # if user instance was found, log user in
        if user:
            if user.is_active:
                # log user in
                login(request, user)
                return redirect(reverse('pub_review:index'))
            else:
                return HttpResponse("Your Pub Reviews account is disabled!")
        else:
            #return HttpResponse("The login details provided were incorrect. ")
            messages.error(request, 'Login Details provided were incorrect')
            return render(request, "pub_review/login.html")

            

    # likely a GET request, serve login page to user
    else:
        return render(request, "pub_review/login.html")

@login_required
def user_logout(request):
# Since we know the user is logged in, we can now just log them out.
    logout(request)
# Take the user back to the homepage.
    return redirect(reverse('pub_review:index'))

def list_pubs(request):
    page = request.GET.get('page', 1)  # Page
    pub_list = Pub.objects.order_by('pubName')

    #search = Seach
    search = request.GET.get("search")

    if search != None:
     pub_list = Pub.objects.filter(pubName__contains=search)

    # Paging
    paginator = Paginator(pub_list, 10)
    page_obj = paginator.get_page(page)

    context = {'pub_list': page_obj}
    return render(request, 'pub_review/search.html', context)

@login_required(login_url='pub_review:login')
def pub_create(request):
    if request.method == 'POST':
        form = PubProfileForm(request.POST, request.FILES) 
        if form.is_valid():
            pub = form.save(commit=False)
            pub.owner = request.user
            pub.save()
            return redirect('pub_review:search')
        else:
            messages.error(request, 'Form Error')
            print(form.errors)

    else:
        form = PubProfileForm()
    context = {'form': form}
    return render(request, 'pub_review/pub_form.html', context={"form":form})

def showPub(request,pub_id):
    pub = get_object_or_404(Pub, pk=pub_id)
    page_review = request.GET.get('page1', 1)
    review = Review.objects.filter(pub=pub)
    review_list = review.order_by('-create_date')

templates/pub_review/Pub_Question_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container my-3">

<!-- Question Object -->
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">
        {{ question.content }}
      </div>
      <div class="d-flex justify-content-end">
        <div class="badge badge-light p-2 text-left">
          <div class ="mb-2">

            <a href="{% url 'pub_review:userProfile' user_id=question.author.id%}">{{ question.author.username }}</a>

          </div>
          <div>{{ question.create_date }}</div>
        </div>
      </div>
      {% if request.user == question.author %}
        <div class="my-3">
          <a href="{% url 'pub_review:Pub_Question_modify' pub_id=pub.id Pub_Question_id=question.id %}" class="btn btn-sm btn-outline-secondary">Edit</a>
          <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pub_review:Pub_Question_delete' pub_id=pub.id Pub_Question_id=question.id %}">Delete</a>
        </div>
      {% endif %}
    </div>
  </div>
<!-- Question Object End -->

<!-- Answer Object -->
  <h5 class="border-bottom my-3 py-2">
    There are {{ question.answer_set.count }} answers
  </h5>
  {% for answer in question.answer_set.all %}
    <div class="card my-3">
      <div class="card-body">
        <div class="card-text" style="white-space:pre-line;">
          {{ answer.content }}
        </div>
        <div class="d-flex justify-content-end">
          <div class="badge badge-light p-2 text-left">
            <div class="mb-2">
              <a href="{% url 'pub_review:userProfile' user_id=answer.author.id%}">{{ answer.author.username }}</a>
            </div>
            <div>{{ answer.create_date }}</div>
            
          </div>
        </div>
        {% if request.user == answer.author %}
        <div class="my-3">
          <a href="{% url 'pub_review:Pub_Answer_modify' pub_id=pub.id Pub_Question_id=question.id Pub_Answer_id=answer.id %}" class="btn btn-sm btn-outline-secondary">Edit</a>
          <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pub_review:Pub_Answer_delete' pub_id=pub.id Pub_Question_id=question.id Pub_Answer_id=answer.id %}">Delete</a>
        </div>
      {% endif %}
      </div>
    </div>
  {% endfor %}
<!-- Answer Object End -->

<!-- Post Answer -->
  <form action="{% url 'pub_review:Pub_Answer_create' pub_id=pub.id Pub_Question_id=question.id %}" method = 'post' class ="my-3">
    {% csrf_token %}

<!-- Function : Handle None value error -->
    {% if form.errors.content %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

<!-- Function End -->
    <div class = "form-group">
      <textarea name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
</div>
{% endblock %}
{% block script %}
<script src="{%static 'delete.js' %}"></script>
{% endblock %}

templates/pub_review/placeholder.html
{% extends 'pub_review/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Placeholder page
{% endblock %}

{% block body_block %}
    <h1>Placeholder page! </h1>
    <div>
        <img src="{% static 'images/placeholder.jpg' %}" alt="placeholder">
    </div>
{% endblock %}

templates/pub_review/pub_detail.html
{% extends 'base.html' %}
{% load PubReviews_filter %}
{% load static %}
{% block content %}
<div class="container white-box">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
      <div class="row">
        <div class="col-md-4 profile-simple border-bottom">
          <div class="d-flex">
            <div class="flex-shrink-0">
              <h3>{{ pub.pubName }}</h3>
              {% if pub.picture %}
                <img width="50%" src="{{ pub.picture.url }}" alt="{{ pub.pubName }}'s Profile Picture">
              {% else %}
                 <p>No picture available.</p>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="col-md-4 border-left border-bottom">
            <div class="d-flex">
              <div class="flex-shrink-0">
                {% if mapURL %}
                <h4>Location</h4>
                    <div id="map">
                    <iframe src="{{mapURL}}" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                {% endif %}
              </div>
            </div>
          </div>
        <div class="col-md-4 border-left border-bottom">
          <div class="row profile-detail">
            <div class="col-6">
                <h3>Owner</h3>
                <a href="{% url 'pub_review:userProfile' user_id=pub.owner.id%}">{{ pub.owner }}</a>
            </div>
            <div class="col-6">
                <h3>City</h3>
                <p>{{ pub.city }}</p>
            </div>
            <div class="col-6">
                <h3>Street</h3>
                <p>{{ pub.streetName }}</p>
            </div>
            <div class="col-6">
                <h3>Postcode</h3>
                <p>{{ pub.postcode }}</p>
            </div>
              <div class="col-6">
                <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{pub.voter.count}}</div>
                    <a href="#" data-uri="{% url 'pub_review:vote_pub' pub.id  %}"
                        class="recommend btn btn-sm btn-secondary btn-block my-1">Recommend</a>
                </div>
            </div>
          </div>
      </div>
      <div class="row">
          <div class="container my-3">
            <h5>Reviews</h5>

              <table class="table">
                <thead>
                <tr class="text-center thead - dark">
                  <th>Number</th>
                  <th style="width:50%" class="text-left">Subject</th>
                  <th>Author</th>
                </tr>
                </thead>
                <tbody>
                {% if review_list %}
                {% for review in review_list %}
                <tr class="text-center">
                    <td>{{ review_list.paginator.count|sub:review_list.start_index|sub:forloop.counter0|add:1 }}</td>
                    <td class="text-left">
                        <a href="{% url 'pub_review:reviewDetail' pub.id review.id %}">{{ review.subject }}</a>
                    </td>
                    <td>
                        <a href="{% url 'pub_review:userProfile' user_id=review.author.id %}">{{ review.author.username}}</a>
                    </td>
                    <!-- Question Object End-->
                </tr>
                {% endfor %}

            <!-- Else -->
                {% else %}
                <tr>
                    <td colspan="3">No Reviews</td>
                </tr>
                {% endif %}
                </tbody>
            <!-- Question list End -->

              </table>
            <!-- Function : Show 10 questions for each page -->
                <ul class="pagination justify-content-center">
                    <!-- Previous Page -->
                    {% if review_list.has_previous %}
                    <li class="page-item">
                        <a class="page-link" data-page="?page1={{ review_list.previous_page_number }}" href="#">Prev</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Prev</a>
                    </li>
                    {% endif %}

                    <!-- Page List -->
                    {% for page_number in review_list.paginator.page_range %}
                    {% if page_number >= review_list.number|add:-5 and page_number <= review_list.number|add:5 %}
                        {% if page_number == review_list.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
                        </li>
                        {% endif %}
                    {% endif %}
                    {% endfor %}

                    <!-- Next Page -->
                    {% if review_list.has_next %}
                    <li class="page-item">
                        <a class="page-link" data-page="{{ review_list.next_page_number }}" href="#">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
                    </li>
                    {% endif %}
                </ul>
                <a href = "{% url 'pub_review:review_create' pub.id%}" class="btn btn-primary">
                    Post a Review
                </a>
          </div>
          <div class="container my-3">
            <h5>Questions</h5>
                <table class="table">
                    <thead>
                        <tr class="text-center thead - dark">
                            <th>Number</th>
                            <th style="width:50%" class="text-left">Subject</th>
                            <th>Author</th>
                            <th>Post Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if question_list %}
                        {% for question in question_list %}
                        <tr class="text-center">
                            <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
                            <td class="text-left">
                                <a href="{% url 'pub_review:Pub_QuestionDetail' pub_id=pub.id Pub_Question_id=question.id %}">{{ question.subject }}</a>
                            </td>
                            <td>
                                <a href="{% url 'pub_review:userProfile' user_id=question.author.id%}"> {{ question.author.username}}</a>
                             </td>
                             <td>
                                 {{ question.create_date}}
                             </td>
                            <!-- Question Object End-->
                        </tr>
                        {% endfor %}
    
                    <!-- Else -->
                        {% else %}
                        <tr>
                            <td colspan="3">No Questions</td>
                        </tr>
                        {% endif %}
                    </tbody>
                    <!-- Question list End -->
    
                </table>
                    <!-- Function : Show 10 questions for each page -->
                    <ul class="pagination justify-content-center">
                            <!-- Previous Page -->
                            {% if question_list.has_previous %}
                            <li class="page-item">
                                <a class="page-link" data-page="?page2={{ question_list.previous_page_number }}" href="#">Prev</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Prev</a>
                            </li>
                            {% endif %}
    
                            <!-- Page List -->
                            {% for page_number in question_list.paginator.page_range %}
                            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                                {% if page_number == question_list.number %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
                                </li>
                                {% else %}
                                <li class="page-item">
                                    <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
                                </li>
                                {% endif %}
                            {% endif %}
                            {% endfor %}
    
                            <!-- Next Page -->
                            {% if question_list.has_next %}
                            <li class="page-item">
                                <a class="page-link" data-page="{{ question_list.next_page_number }}" href="#">Next</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
                            </li>
                            {% endif %}
                        </ul>
                        <a href = "{% url 'pub_review:Pub_Question_create' pub.id%}" class="btn btn-primary">
                            Ask a Question
                        </a>
                  </div>
        </div>
    </div>
    {% if request.user == pub.owner %}
    <div class="col-md-3">
          <a href="{% url 'pub_review:pub_modify' pub_id=pub.id%}" class="btn btn-sm btn-outline-secondary">Edit the Pub</a>
          <a href="#" class="delete btn btn-sm btn-outline-danger" data-uri="{% url 'pub_review:pub_delete' pub_id=pub.id %}">Delete the pub</a>
    </div>
    {% endif %}
{% endblock %}
{% block script %}
<script src="{%static 'delete.js' %}"></script>
<script src="{%static 'recommend.js' %}"></script>
{% endblock %}