pub_review/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name= 'pub_review'
urlpatterns = [
    path('',views.index, name ='index'),

    # Question and Answer URLs
    path('questions/',views.list_questions,name="questions"),
    path('question/<int:question_id>/',views.detail, name = 'detail'),
    path('question/create/',views.question_create, name = 'question_create'),
    path('answer/create/<int:question_id>/',views.answer_create, name = 'answer_create'),
    path('question/modify/<int:question_id>/',views.question_modify,name='question_modify'),
    path('question/delete/<int:question_id>/',views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/',views.answer_modify,name='answer_modify'),
    path('answer/delete/<int:answer_id>/',views.answer_delete, name='answer_delete'),


    # Login URLs
    path('login/',views.user_login, name= 'login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),

    # Pub URLs
    path('search/',views.list_pubs, name='search'),
    path('pub/<int:pub_id>/',views.showPub,name="pubDetail"),
    path('pub/create/',views.pub_create, name= 'pub_create'),
    path('pub/modify/<int:pub_id>/',views.pub_modify,name='pub_modify'),
    path('pub/delete/<int:pub_id>/',views.pub_delete, name='pub_delete'),

    #Review URLs
    path('pub/<int:pub_id>/review/<int:review_id>/',views.showReview, name = 'reviewDetail'),
    path('pub/<int:pub_id>/review/create/',views.review_create, name = 'review_create'),
    path('pub/<int:pub_id>/review/modify/<int:review_id>/',views.review_modify,name='review_modify'),
    path('pub/<int:pub_id>/review/delete/<int:review_id>/',views.review_delete, name='review_delete'),

    #Pub_Question URLs
    path('pub/<int:pub_id>/question/<int:Pub_Question_id>/',views.showPub_Question, name = 'Pub_QuestionDetail'),
    path('pub/<int:pub_id>/question/create/',views.Pub_Question_create, name = 'Pub_Question_create'),
    path('pub/<int:pub_id>/question/<int:Pub_Question_id>/answer/create/',views.Pub_Answer_create, name = 'Pub_Answer_create'),
    path('pub/<int:pub_id>/question/modify/<int:Pub_Question_id>/',views.Pub_Question_modify,name='Pub_Question_modify'),
    path('pub/<int:pub_id>/question/delete/<int:Pub_Question_id>/',views.Pub_Question_delete, name='Pub_Question_delete'),
    path('pub/<int:pub_id>/question/<int:Pub_Question_id>/answer/modify/<int:Pub_Answer_id>/',views.Pub_Answer_modify,name='Pub_Answer_modify'),
    path('pub/<int:pub_id>/question/<int:Pub_Question_id>/answer/delete/<int:Pub_Answer_id>/',views.Pub_Answer_delete, name='Pub_Answer_delete'),

    #User URLs
    path('user/<int:user_id>/',views.showUserProfile,name="userProfile"),
    path('user/modify/<int:user_id>/',views.userProfile_modify,name='user_modify'),
    path('user/delete/<int:user_id>/',views.userProfile_delete, name='user_delete'),

    #Voter URLs
    path('vote/pub/<int:pub_id>/',views.vote_pub,name="vote_pub"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team4b_pub_review/urls.py
from django.contrib import admin
from django.urls import include, path
from pub_review import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('pub-review/', include('pub_review.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
{% load static %}

<html lang = "en">
<head>
    <meta charset = "utf-8">
    <meta name= "viewport" content= "width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Pub Reviews</title>
    {% block extra_head %}{% endblock %}
</head>
<body>
<!----- Navigation Bar ----->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pub_review:index' %}">Pub <span>Reviews</span></a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pub_review:search' %}">Search</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href= "{% url 'pub_review:questions' %}">Q&A</a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'pub_review:logout' %}">Log Out</a>
                {% else %}
                <a class="nav-link" href="{% url 'pub_review:login' %}">Login/Sign Up</a>
                {% endif %}
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'pub_review:user_modify' user.id %}">Edit Profile</a>
                {% endif %}
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'pub_review:userProfile' user.id %}">User Profile</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>
<!----- Navigation Bar End ----->
{% block content %}
{% endblock %}
<script src="{%static 'jquery-3.7.1.min.js' %}"></script>
<script src="{%static 'bootstrap.min.js' %}"></script>

<!--- JS Start --->
{% block script %}
{% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
{% for field in form %}
    {% for error in field.errors %}  <!-- Print error -->
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ error }}
        </div>
    {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}   <!-- Print Non-field error -->
    <div class="alert alert-danger">
        <strong>{{ error }}</strong>
    </div>
{% endfor %}
{% endif %}